/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* Daily challenge: one puzzle per calendar day, the same for everyone, plus a
   streak, streak freezes, and a replay calendar.

   Day boundary is UTC. strimko already does it this way; pips uses local
   midnight. Standardising on UTC matters the moment a leaderboard exists —
   otherwise "today's puzzle" means different things in different timezones and
   a global daily ranking is meaningless. The cost is that a player in UTC-8
   rolls over at 4pm local; that is the normal trade every daily-puzzle game
   makes, and it is at least consistent.

   Freezes are Bullpen's "hay bales": miss a day and a freeze is spent instead
   of the streak resetting. They are earned by keeping the streak going, and
   capped, so they soften a bad week without making the streak meaningless.

   The clock is injectable (opts.now) because there is no way to test a streak
   across a month otherwise. */

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.MetaDaily = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {

  var VERSION = 1;
  var DAY_MS = 86400000;

  function dayNumber(date) {
    var d = date == null ? new Date() : (typeof date === "number" ? new Date(date) : date);
    return Math.floor(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()) / DAY_MS);
  }

  function pad(n) { return (n < 10 ? "0" : "") + n; }

  function dateKeyOf(date) {
    var d = date == null ? new Date() : (typeof date === "number" ? new Date(date) : date);
    return d.getUTCFullYear() + "-" + pad(d.getUTCMonth() + 1) + "-" + pad(d.getUTCDate());
  }

  function dayToDate(day) {
    return new Date(day * DAY_MS);
  }

  function dayToKey(day) {
    return dateKeyOf(dayToDate(day));
  }

  function keyToDay(key) {
    var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(key || ""));
    if (!m) return null;
    return Math.floor(Date.UTC(+m[1], +m[2] - 1, +m[3]) / DAY_MS);
  }

  /* Every public method accepts whatever the caller has to hand: a date key
     string ("2026-03-02"), a day number, a ms timestamp, a Date, or null for
     today. Games mostly carry the date key around, so refusing it would push
     conversion noise into every call site. */
  function toDay(date, nowFn) {
    if (date == null) return dayNumber(nowFn ? nowFn() : Date.now());
    if (typeof date === "string") {
      var d = keyToDay(date);
      return d == null ? dayNumber(nowFn ? nowFn() : Date.now()) : d;
    }
    if (typeof date === "number") {
      // A day number is ~20k; a ms timestamp is ~1.7e12. Nothing lands between.
      return date < 1e6 ? Math.floor(date) : dayNumber(date);
    }
    return dayNumber(date);
  }

  function blank() {
    return {
      v: VERSION,
      streak: 0,
      best: 0,
      lastDay: null,
      freezes: 0,
      freezeProgress: 0,     // days since the last freeze was earned
      totalSolved: 0,
      days: {}               // dateKey -> {day, ms, stars, tier, hints, mistakes}
    };
  }

  function Daily(opts) {
    if (!(this instanceof Daily)) return new Daily(opts);
    this.store = opts.store;
    this.key = opts.key || "daily";
    this.now = opts.now || function () { return Date.now(); };
    this.tierByDow = opts.tierByDow || null;   // [Sun..Sat] tier keys
    this.tier = opts.tier || null;             // or one fixed tier
    this.levelsPerTier = opts.levelsPerTier || 0;
    this.planFn = opts.plan || null;
    this.freezeCfg = opts.freezes || { max: 3, earnEvery: 7 };
    this.starsFor = opts.starsFor || null;
    this.par = opts.par || 0;
    this.firstDay = opts.firstDay ? keyToDay(opts.firstDay) : null;

    this.state = this.store.get(this.key, null) || blank();
    if (this.state.v !== VERSION) this.state = blank();
    if (!this.state.days) this.state.days = {};
  }

  Daily.prototype.save = function () {
    this.store.set(this.key, this.state);
  };

  Daily.prototype.today = function () {
    return dayNumber(this.now());
  };

  /* Which puzzle is day D? Deterministic, so every device agrees and any past
     day can be regenerated for the replay calendar. */
  Daily.prototype.plan = function (date) {
    var day = toDay(date, this.now);
    if (this.planFn) return this.planFn(day, dayToKey(day));
    var tier = this.tier;
    if (this.tierByDow) {
      var dow = dayToDate(day).getUTCDay();
      tier = this.tierByDow[dow];
    }
    var index = this.levelsPerTier ? (((day % this.levelsPerTier) + this.levelsPerTier) % this.levelsPerTier) + 1 : day;
    return { day: day, dateKey: dayToKey(day), tier: tier, index: index };
  };

  Daily.prototype.entry = function (dateKey) {
    return this.state.days[dateKey] || null;
  };

  Daily.prototype.isSolved = function (dateKey) {
    return !!this.state.days[dateKey];
  };

  /* Is this day playable at all? Not the future, and not before the game
     shipped (config.firstDay), so the calendar can grey those out. */
  Daily.prototype.isPlayable = function (day) {
    if (day > this.today()) return false;
    if (this.firstDay != null && day < this.firstDay) return false;
    return true;
  };

  /* Record a solve. Idempotent per day: replaying a day you already solved
     returns alreadySolved and changes nothing — that's what makes strimko's
     "review" mode safe to re-enter. */
  Daily.prototype.record = function (date, res) {
    res = res || {};
    var day = toDay(date, this.now);
    var key = dayToKey(day);
    var s = this.state;

    if (s.days[key]) {
      return {
        alreadySolved: true, streak: s.streak, best: s.best,
        freezes: s.freezes, freezesUsed: 0, isNewBest: false,
        stars: s.days[key].stars || 0, ms: s.days[key].ms || 0
      };
    }

    var stars = this.starsFor
      ? this.starsFor({ ms: res.ms || 0, hints: res.hints || 0, mistakes: res.mistakes || 0 }, res.par || this.par)
      : 0;

    s.days[key] = {
      day: day, ms: res.ms || 0, stars: stars,
      tier: res.tier || null, hints: res.hints || 0, mistakes: res.mistakes || 0
    };
    s.totalSolved += 1;

    /* Streak. Only a solve for the CURRENT day extends it — back-filling an
       old day from the calendar counts as a solve and shows on the calendar,
       but does not retroactively rewrite streak history. Doing otherwise makes
       the streak trivially farmable and the number stops meaning anything. */
    var freezesUsed = 0;
    var today = this.today();
    var extended = false;
    if (day === today) {
      if (s.lastDay === null) {
        s.streak = 1;
        extended = true;
      } else if (day > s.lastDay) {
        var missed = day - s.lastDay - 1;
        if (missed === 0) {
          s.streak += 1;
          extended = true;
        } else if (s.freezes >= missed) {
          s.freezes -= missed;
          freezesUsed = missed;
          s.streak += 1;
          extended = true;
        } else {
          s.streak = 1;
          s.freezes = 0;
          s.freezeProgress = 0;
        }
      }
      if (day > (s.lastDay === null ? -Infinity : s.lastDay)) s.lastDay = day;

      // Earn a freeze every N consecutive days, up to the cap.
      if (extended) {
        s.freezeProgress = (s.freezeProgress || 0) + 1;
        if (s.freezeProgress >= this.freezeCfg.earnEvery) {
          s.freezeProgress = 0;
          if (s.freezes < this.freezeCfg.max) s.freezes += 1;
        }
      }
    }

    var isNewBest = s.streak > (s.best || 0);
    if (isNewBest) s.best = s.streak;

    this.save();

    return {
      alreadySolved: false, streak: s.streak, best: s.best,
      freezes: s.freezes, freezesUsed: freezesUsed, isNewBest: isNewBest,
      stars: stars, ms: res.ms || 0, backfill: day !== today
    };
  };

  /* The streak as it reads RIGHT NOW — the stored number is only accurate up
     to lastDay. If enough days have passed without a solve, the streak is
     already dead (or living on freezes) before the next solve is recorded, and
     the home screen must say so. Read-only: nothing is spent until a solve. */
  Daily.prototype.currentStreak = function () {
    var s = this.state;
    if (s.lastDay === null) return { streak: 0, atRisk: false, freezes: s.freezes, dead: false };
    var gap = this.today() - s.lastDay;
    if (gap <= 0) return { streak: s.streak, atRisk: false, freezes: s.freezes, dead: false };
    if (gap === 1) return { streak: s.streak, atRisk: true, freezes: s.freezes, dead: false };
    var missed = gap - 1;
    if (s.freezes >= missed) {
      return { streak: s.streak, atRisk: true, freezes: s.freezes - missed, dead: false, wouldSpend: missed };
    }
    return { streak: 0, atRisk: false, freezes: 0, dead: true, was: s.streak };
  };

  /* One month for the replay calendar. `date` is any date in the month. */
  Daily.prototype.calendar = function (date) {
    var d = date == null ? new Date(this.now()) : (typeof date === "number" ? new Date(date) : date);
    var y = d.getUTCFullYear(), m = d.getUTCMonth();
    var first = Math.floor(Date.UTC(y, m, 1) / DAY_MS);
    var daysInMonth = new Date(Date.UTC(y, m + 1, 0)).getUTCDate();
    var out = [];
    for (var i = 0; i < daysInMonth; i++) {
      var day = first + i;
      var key = dayToKey(day);
      var e = this.state.days[key];
      out.push({
        day: day,
        dateKey: key,
        dom: i + 1,
        dow: dayToDate(day).getUTCDay(),
        solved: !!e,
        ms: e ? e.ms : 0,
        stars: e ? e.stars : 0,
        isToday: day === this.today(),
        playable: this.isPlayable(day)
      });
    }
    return { year: y, month: m, days: out };
  };

  Daily.prototype.stats = function () {
    var s = this.state, keys = Object.keys(s.days), bestMs = 0, sum = 0;
    for (var i = 0; i < keys.length; i++) {
      var ms = s.days[keys[i]].ms || 0;
      if (ms && (!bestMs || ms < bestMs)) bestMs = ms;
      sum += ms;
    }
    return {
      solved: keys.length, streak: s.streak, best: s.best,
      freezes: s.freezes, bestMs: bestMs,
      avgMs: keys.length ? Math.round(sum / keys.length) : 0
    };
  };

  Daily.toDay = toDay;
  Daily.dayNumber = dayNumber;
  Daily.dateKeyOf = dateKeyOf;
  Daily.dayToKey = dayToKey;
  Daily.keyToDay = keyToDay;
  Daily.DAY_MS = DAY_MS;
  return Daily;
});
