/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* GameMeta — mounts the whole meta-layer from one config object.

   A game does this once:

     var Meta = GameMeta.create({
       id: "nonograms",
       prefix: "nono",
       tiers: [
         { key: "s5",  name: "5x5",   levels: 50, par: function (n) { return 60000; } },
         { key: "s20", name: "20x20", levels: 50, par: parFor, requires: { cleared: 60 } }
       ],
       daily: { tierByDow: ["s10","s5","s10","s10","s15","s15","s20"], freezes: { max: 3, earnEvery: 7 } },
       curves: require("./rank-curves.json")
     });

   ...and then calls Meta.recordWin() in exactly one place — the game's existing
   win handler. Everything else (level map, calendar, records panel, rank badge)
   reads from the returned object.

   Deliberately NOT included: anything that touches the DOM. Games differ far
   too much in markup for a shared renderer to be worth it, and the moment this
   library renders anything it stops being droppable into nine different games. */

(function (root, factory) {
  var api;
  if (typeof module !== "undefined" && module.exports) {
    api = factory(
      require("./store.js"),
      require("./progress.js"),
      require("./daily.js"),
      require("./records.js"),
      require("./rank.js"),
      require("./rng.js")
    );
    module.exports = api;
  } else {
    api = factory(root.MetaStore, root.MetaProgress, root.MetaDaily, root.MetaRecords, root.MetaRank, root.MetaRng);
    root.GameMeta = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function (Store, Progress, Daily, Records, Rank, Rng) {

  function create(config) {
    config = config || {};
    var prefix = config.prefix || config.id || "game";
    var store = new Store(prefix, config.backing);
    var now = config.now || function () { return Date.now(); };
    var tiers = config.tiers || [];
    var dailyCfg = config.daily || {};

    var progress = new Progress({
      store: store, tiers: tiers, starsFor: config.starsFor
    });
    var records = new Records({ store: store });
    var rank = new Rank({
      store: store, game: config.id || prefix,
      curves: config.curves || {}, now: now, sender: config.sender
    });
    var daily = new Daily({
      store: store, now: now,
      tier: dailyCfg.tier, tierByDow: dailyCfg.tierByDow,
      levelsPerTier: dailyCfg.levelsPerTier, plan: dailyCfg.plan,
      freezes: dailyCfg.freezes, firstDay: dailyCfg.firstDay,
      starsFor: config.starsFor || Progress.defaultStars,
      par: dailyCfg.par
    });

    function tierDef(key) {
      for (var i = 0; i < tiers.length; i++) if (tiers[i].key === key) return tiers[i];
      return null;
    }

    var Meta = {
      config: config,
      store: store,
      progress: progress,
      daily: daily,
      records: records,
      rank: rank,
      rng: Rng,
      tiers: tiers,
      tierDef: tierDef,

      /* The seed for a given level. Deterministic from (game, tier, level), so
         a level is stored as a number and rebuilt identically everywhere. */
      seedFor: function (tierKey, level) {
        return Rng.hashSeed((config.id || prefix) + "-" + tierKey + "-" + level);
      },

      /* THE hook. Call from the game's win handler with:
           {mode, tier, level|dateKey, ms, hints, mistakes}
         mode is "level" (campaign), "daily", or "free" (no progression).
         Returns everything a win screen needs, in one object. */
      recordWin: function (ctx) {
        ctx = ctx || {};
        var mode = ctx.mode || "level";
        var out = {
          mode: mode, tier: ctx.tier, level: ctx.level || 0,
          ms: ctx.ms || 0, hints: ctx.hints || 0, mistakes: ctx.mistakes || 0
        };

        if (mode === "level") {
          out.progress = progress.recordWin(ctx.tier, ctx.level, ctx);
          out.stars = out.progress.stars;
        } else if (mode === "daily") {
          out.daily = daily.record(ctx.dateKey || ctx.day, ctx);
          out.stars = out.daily.stars;
          out.alreadySolved = out.daily.alreadySolved;
        }

        // Free play and an already-solved daily replay are not achievements —
        // they must not pollute personal bests or the rank queue.
        var counts = !(mode === "free") && !out.alreadySolved;
        if (counts) {
          out.records = records.record(ctx.tier, ctx.ms);
          out.rankPercentile = rank.percentile(ctx.tier, ctx.ms);
          rank.submit({
            mode: mode, tier: ctx.tier, level: ctx.level,
            dateKey: ctx.dateKey, ms: ctx.ms, stars: out.stars,
            hints: ctx.hints, mistakes: ctx.mistakes
          });
        }

        return out;
      },

      /* One snapshot for the home screen. */
      home: function () {
        var streak = daily.currentStreak();
        var plan = daily.plan();
        var t = progress.totals();
        return {
          totalStars: t.totalStars,
          solvedCount: t.solvedCount,
          clearedCount: t.clearedCount,
          daily: {
            plan: plan,
            solvedToday: daily.isSolved(plan.dateKey),
            streak: streak.streak,
            atRisk: streak.atRisk,
            dead: streak.dead,
            freezes: streak.freezes
          },
          tiers: tiers.map(function (def) {
            var open = progress.isTierUnlocked(def.key);
            var ts = progress.tierState(def.key);
            return {
              key: def.key, name: def.name, levels: def.levels || 0,
              unlocked: open, gate: progress.tierGate(def.key),
              reached: ts.unlocked, next: progress.nextLevel(def.key),
              records: records.get(def.key)
            };
          })
        };
      },

      /* Wipe everything this game stored. Used by a "reset progress" button. */
      reset: function () {
        store.clear();
      }
    };

    return Meta;
  }

  return {
    create: create,
    Store: Store, Progress: Progress, Daily: Daily,
    Records: Records, Rank: Rank, Rng: Rng
  };
});
