/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* Global ranking — the seam, deliberately not yet wired to a backend.

   Nothing in the portfolio makes a network call today, and the decision was to
   ship the local half first. So this module does three things now:

     1. Owns the anonymous identity (device UUID + a nickname), so a backend can
        be added later without asking anyone to re-register.
     2. Queues every result durably. Scores earned before the backend existed
        are not lost — flush() replays them the first time a sender is wired in.
     3. Answers percentile("Top 12%") from a BAKED distribution curve, and says
        so via source:"local". When the real service lands, only submit() and
        percentile() change; no game code moves.

   The curves are per tier, generated offline from real solve data, and stored
   as ascending [ms, cumulativePercent] pairs — cumulativePercent being the
   share of players who finish in that time or faster. */

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.MetaRank = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {

  var VERSION = 1;
  var QUEUE_CAP = 500;

  function uuid() {
    try {
      if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
    } catch (e) {}
    // Not security-sensitive — it only has to be unique per device.
    var s = "";
    for (var i = 0; i < 32; i++) {
      s += ((Math.random() * 16) | 0).toString(16);
      if (i === 7 || i === 11 || i === 15 || i === 19) s += "-";
    }
    return s;
  }

  function blank() {
    return { v: VERSION, uuid: null, nickname: null, queue: [], sentCount: 0 };
  }

  function Rank(opts) {
    if (!(this instanceof Rank)) return new Rank(opts);
    this.store = opts.store;
    this.key = opts.key || "rank";
    this.game = opts.game || "game";
    this.curves = opts.curves || {};
    this.now = opts.now || function () { return Date.now(); };
    this.sender = opts.sender || null;    // future: function(batch) -> Promise

    this.state = this.store.get(this.key, null) || blank();
    if (this.state.v !== VERSION) this.state = blank();
    if (!this.state.queue) this.state.queue = [];
    if (!this.state.uuid) {
      this.state.uuid = uuid();
      this.save();
    }
  }

  Rank.prototype.save = function () {
    this.store.set(this.key, this.state);
  };

  Rank.prototype.identity = function () {
    return { uuid: this.state.uuid, nickname: this.state.nickname };
  };

  Rank.prototype.hasNickname = function () {
    return !!this.state.nickname;
  };

  /* 3-12 chars, letters/digits/_- only. Returns {ok, nickname} or {ok:false,
     error} so the UI can show why it was rejected. */
  Rank.prototype.setNickname = function (name) {
    name = String(name == null ? "" : name).trim();
    if (name.length < 3) return { ok: false, error: "Name needs at least 3 characters" };
    if (name.length > 12) return { ok: false, error: "Name can be at most 12 characters" };
    if (!/^[A-Za-z0-9_\-]+$/.test(name)) return { ok: false, error: "Letters, numbers, - and _ only" };
    this.state.nickname = name;
    this.save();
    return { ok: true, nickname: name };
  };

  /* Queue a result. No network yet — this is a durable buffer, capped so a
     player who never connects doesn't grow localStorage without bound (oldest
     entries are dropped first). */
  Rank.prototype.submit = function (result) {
    var row = {
      game: this.game,
      mode: result.mode || "level",        // level | daily | free
      tier: result.tier || null,
      level: result.level || null,
      dateKey: result.dateKey || null,
      ms: result.ms || 0,
      stars: result.stars || 0,
      hints: result.hints || 0,
      mistakes: result.mistakes || 0,
      at: this.now()
    };
    this.state.queue.push(row);
    while (this.state.queue.length > QUEUE_CAP) this.state.queue.shift();
    this.save();
    return row;
  };

  Rank.prototype.pending = function () {
    return this.state.queue.slice();
  };

  Rank.prototype.pendingCount = function () {
    return this.state.queue.length;
  };

  /* Wire a sender later and call this; the queue only clears on success, so a
     failed flush leaves everything intact for the next attempt. */
  Rank.prototype.flush = function (sender) {
    var send = sender || this.sender;
    var self = this;
    if (!send || !this.state.queue.length) {
      return Promise.resolve({ sent: 0, source: "local" });
    }
    var batch = this.state.queue.slice();
    return Promise.resolve(send(batch, this.identity())).then(function (res) {
      // Only drop what was actually sent — new results may have queued meanwhile.
      self.state.queue = self.state.queue.slice(batch.length);
      self.state.sentCount += batch.length;
      self.save();
      return { sent: batch.length, source: "remote", response: res };
    }, function (err) {
      return { sent: 0, source: "local", error: err };
    });
  };

  /* Linear interpolation over the baked curve. Returns the share of players
     who are at least as fast — so a smaller number is a better result, which
     is what "Top 5%" means. */
  Rank.prototype.percentile = function (tierKey, ms) {
    var curve = this.curves[tierKey];
    if (!curve || !curve.length || !ms) return null;

    var pct;
    if (ms <= curve[0][0]) {
      // Faster than the fastest breakpoint — scale down toward 1%, don't clamp
      // flat, so a genuinely exceptional time still reads as exceptional.
      pct = Math.max(1, curve[0][1] * (ms / curve[0][0]));
    } else if (ms >= curve[curve.length - 1][0]) {
      pct = curve[curve.length - 1][1];
    } else {
      for (var i = 1; i < curve.length; i++) {
        if (ms <= curve[i][0]) {
          var lo = curve[i - 1], hi = curve[i];
          var span = hi[0] - lo[0];
          var t = span ? (ms - lo[0]) / span : 0;
          pct = lo[1] + t * (hi[1] - lo[1]);
          break;
        }
      }
    }

    pct = Math.min(99, Math.max(1, pct));
    var rounded = Math.round(pct);
    return {
      pct: pct,
      label: rounded >= 99 ? "Bottom 1%" : "Top " + rounded + "%",
      beats: Math.round(100 - pct),
      source: "local"
    };
  };

  Rank.prototype.hasCurve = function (tierKey) {
    return !!(this.curves[tierKey] && this.curves[tierKey].length);
  };

  Rank.uuid = uuid;
  return Rank;
});
