/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* Personal bests — the "competing with yourself" layer.

   Progress already stores a best time per level. This is the wider view: per
   tier and overall, so the win screen can say "New best for 10x10 — 12s faster
   than your record" and the home screen can show an average that visibly drops
   as someone improves.

   Keeps only the last N times per tier (not the full history) so the record
   stays a small, bounded object no matter how much someone plays. */

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.MetaRecords = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {

  var VERSION = 1;
  var RECENT = 10;

  function blank() {
    return { v: VERSION, tiers: {} };
  }

  function blankTier() {
    return { wins: 0, bestMs: 0, worstMs: 0, totalMs: 0, recent: [] };
  }

  function Records(opts) {
    if (!(this instanceof Records)) return new Records(opts);
    this.store = opts.store;
    this.key = opts.key || "records";
    this.recent = opts.recent || RECENT;
    this.state = this.store.get(this.key, null) || blank();
    if (this.state.v !== VERSION) this.state = blank();
    if (!this.state.tiers) this.state.tiers = {};
  }

  Records.prototype.save = function () {
    this.store.set(this.key, this.state);
  };

  Records.prototype.tier = function (tierKey) {
    var t = this.state.tiers[tierKey];
    if (!t) {
      t = blankTier();
      this.state.tiers[tierKey] = t;
    }
    if (!t.recent) t.recent = [];
    return t;
  };

  /* Returns the delta against the previous best, which is the number the win
     screen actually wants: "12s faster than your record". */
  Records.prototype.record = function (tierKey, ms) {
    ms = ms || 0;
    var t = this.tier(tierKey);
    var prevBest = t.bestMs || 0;

    t.wins += 1;
    t.totalMs += ms;
    if (ms) {
      if (!t.bestMs || ms < t.bestMs) t.bestMs = ms;
      if (ms > t.worstMs) t.worstMs = ms;
      t.recent.push(ms);
      while (t.recent.length > this.recent) t.recent.shift();
    }

    this.save();

    var isNewBest = !!ms && (!prevBest || ms < prevBest);
    return {
      isNewBest: isNewBest,
      // Only meaningful when there was a previous best to beat.
      deltaMs: isNewBest && prevBest ? prevBest - ms : 0,
      prevBestMs: prevBest,
      bestMs: t.bestMs,
      avgMs: t.wins ? Math.round(t.totalMs / t.wins) : 0,
      recentAvgMs: t.recent.length ? Math.round(t.recent.reduce(function (a, b) { return a + b; }, 0) / t.recent.length) : 0,
      wins: t.wins
    };
  };

  Records.prototype.get = function (tierKey) {
    var t = this.tier(tierKey);
    return {
      wins: t.wins,
      bestMs: t.bestMs,
      worstMs: t.worstMs,
      avgMs: t.wins ? Math.round(t.totalMs / t.wins) : 0,
      recentAvgMs: t.recent.length ? Math.round(t.recent.reduce(function (a, b) { return a + b; }, 0) / t.recent.length) : 0,
      recent: t.recent.slice()
    };
  };

  /* Are they actually getting better?

     Compares the recent window against everything BEFORE it — not against the
     lifetime average, which includes the recent window and so drags the
     comparison toward itself. Until the window has overflowed at least once
     the two are literally the same number, and the trend would always read
     "flat" no matter how much someone improved.

     The earlier average is recoverable without storing the full history:
     lifetime total minus the recent window, over the counts that differ. */
  Records.prototype.trend = function (tierKey) {
    var t = this.tier(tierKey);
    var half = Math.max(2, Math.ceil(this.recent / 2));
    if (t.wins < half * 2 || !t.recent.length) {
      return { trendMs: 0, improving: false, enough: false };
    }

    var recentSum = 0;
    for (var i = 0; i < t.recent.length; i++) recentSum += t.recent[i];
    var recentAvg = recentSum / t.recent.length;

    var earlierWins = t.wins - t.recent.length;
    var earlierAvg;
    if (earlierWins > 0) {
      earlierAvg = (t.totalMs - recentSum) / earlierWins;
    } else {
      // The window still holds everything — split it in half instead.
      var mid = Math.floor(t.recent.length / 2);
      var firstSum = 0;
      for (var j = 0; j < mid; j++) firstSum += t.recent[j];
      var lastSum = recentSum - firstSum;
      earlierAvg = firstSum / mid;
      recentAvg = lastSum / (t.recent.length - mid);
    }

    if (!earlierAvg || !recentAvg) return { trendMs: 0, improving: false, enough: false };
    return {
      trendMs: Math.round(recentAvg - earlierAvg),
      improving: recentAvg < earlierAvg,
      earlierAvgMs: Math.round(earlierAvg),
      recentAvgMs: Math.round(recentAvg),
      enough: true
    };
  };

  Records.prototype.all = function () {
    var out = {}, keys = Object.keys(this.state.tiers);
    for (var i = 0; i < keys.length; i++) out[keys[i]] = this.get(keys[i]);
    return out;
  };

  return Records;
});
