/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* Namespaced, versioned localStorage — replacing the six copy-pasted
   lsGet/lsSet/lsDel helpers across the portfolio.

   Two things it adds over the copies:

   1. A prefix, so every game's keys are "<prefix>:<name>" and a single
      clear() can wipe one game without touching another on the same origin.
   2. migrate(name, version, fn) — a one-shot, idempotent upgrade hook. The
      retrofits need this: existing players already have data under legacy keys
      like "nonograms.save.v1", and it must survive.

   The backing store is injectable so the whole library is testable under Node,
   where there is no localStorage — same trick as CatDoku/js/storage.js. Every
   access is wrapped: Safari in private mode throws on setItem, and a game must
   stay playable when persistence isn't available. */

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.MetaStore = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {

  /* An in-memory stand-in with the localStorage surface we use. Also the
     fallback when localStorage is missing or throws on first touch. */
  function memoryStore() {
    var map = {};
    return {
      getItem: function (k) { return Object.prototype.hasOwnProperty.call(map, k) ? map[k] : null; },
      setItem: function (k, v) { map[k] = String(v); },
      removeItem: function (k) { delete map[k]; },
      key: function (i) { return Object.keys(map)[i]; },
      get length() { return Object.keys(map).length; }
    };
  }

  function defaultBacking() {
    try {
      var ls = (typeof localStorage !== "undefined") ? localStorage : null;
      if (!ls) return memoryStore();
      // Probe: private-mode Safari exposes localStorage but throws on write.
      var probe = "__meta_probe__";
      ls.setItem(probe, "1");
      ls.removeItem(probe);
      return ls;
    } catch (e) {
      return memoryStore();
    }
  }

  var SCHEMA = "__schema";

  function Store(prefix, backing) {
    if (!(this instanceof Store)) return new Store(prefix, backing);
    this.prefix = prefix;
    this.backing = backing || defaultBacking();
  }

  Store.prototype.key = function (name) {
    return this.prefix + ":" + name;
  };

  Store.prototype.get = function (name, fallback) {
    try {
      var raw = this.backing.getItem(this.key(name));
      if (raw === null || raw === undefined) return fallback;
      var val = JSON.parse(raw);
      return val === null || val === undefined ? fallback : val;
    } catch (e) {
      return fallback;
    }
  };

  Store.prototype.set = function (name, value) {
    try {
      this.backing.setItem(this.key(name), JSON.stringify(value));
      return true;
    } catch (e) {
      return false;   // quota or private mode — the caller keeps playing
    }
  };

  Store.prototype.del = function (name) {
    try { this.backing.removeItem(this.key(name)); } catch (e) {}
  };

  Store.prototype.has = function (name) {
    try { return this.backing.getItem(this.key(name)) !== null; } catch (e) { return false; }
  };

  /* Read a raw (un-prefixed) key. The migrations need this to reach legacy
     data written before the store existed. */
  Store.prototype.getRaw = function (key, fallback) {
    try {
      var raw = this.backing.getItem(key);
      if (raw === null || raw === undefined) return fallback;
      return JSON.parse(raw);
    } catch (e) {
      return fallback;
    }
  };

  Store.prototype.delRaw = function (key) {
    try { this.backing.removeItem(key); } catch (e) {}
  };

  /* Run `fn` once, when the stored schema version for `name` is below
     `version`. fn receives the current value (or undefined) and returns the
     upgraded value; returning undefined leaves the slot untouched but still
     records the version, so a pure cleanup migration is expressible.

     Idempotent by construction: the version is recorded even when fn is a
     no-op, so a second call on the same data does nothing. */
  Store.prototype.migrate = function (name, version, fn) {
    var schema = this.get(SCHEMA, {});
    var at = schema[name] || 0;
    if (at >= version) return false;
    var next;
    try {
      next = fn(this.get(name, undefined), at);
    } catch (e) {
      return false;   // a broken migration must not brick the game
    }
    if (next !== undefined) this.set(name, next);
    schema[name] = version;
    this.set(SCHEMA, schema);
    return true;
  };

  Store.prototype.schemaVersion = function (name) {
    return (this.get(SCHEMA, {})[name]) || 0;
  };

  /* Remove every key belonging to this prefix. */
  Store.prototype.clear = function () {
    var doomed = [];
    try {
      for (var i = 0; i < this.backing.length; i++) {
        var k = this.backing.key(i);
        if (k && k.indexOf(this.prefix + ":") === 0) doomed.push(k);
      }
    } catch (e) { return; }
    for (var j = 0; j < doomed.length; j++) this.delRaw(doomed[j]);
  };

  Store.memoryStore = memoryStore;
  return Store;
});
